# https://github.com/grafana/helm-charts/blob/grafana-7.3.11/charts/grafana/values.yaml

testFramework:
  enabled: false

admin:
  existingSecret: admin-creds
  userKey: username
  passwordKey: password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring-metrics.svc.cluster.local
      - name: Loki
        type: loki
        url: http://loki.monitoring-logs.svc.cluster.local:3100

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    announcers:
      url: https://raw.githubusercontent.com/DanNixon/emfcamp-2024/main/cloud-apps/grafana/dashboards/announcers.json
    api-adapter:
      url: https://raw.githubusercontent.com/DanNixon/emfcamp-2024/main/cloud-apps/grafana/dashboards/api-adapter.json
    dad-joke-hotline:
      url: https://raw.githubusercontent.com/DanNixon/emfcamp-2024/main/cloud-apps/grafana/dashboards/dad-joke-hotline.json
    dial-a-schedule:
      url: https://raw.githubusercontent.com/DanNixon/emfcamp-2024/main/cloud-apps/grafana/dashboards/dial-a-schedule.json
