{
 "title": "Announcers",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "schedule_announcer_events",
     "legendFormat": "{{namespace}}/{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Time to next event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "schedule_announcer_time_to_next_event",
     "legendFormat": "{{namespace}}/{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Schedule Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "schedule_announcer_schedule_updates",
     "legendFormat": "{{namespace}}/{{app_kubernetes_io_name}} - {{result}} - {{changes}}"
    }
   ]
  },
  { "title": "DAPNET", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Announcements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "targets": [
    { "expr": "dapnet_event_announcements", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=\"dapnet-schedule-announcer\"} |= `WARN` or `ERROR` or `panic`"
    }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Announcements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "mqtt_event_announcements{namespace=\"schedule-mqtt-announcer\"}",
     "legendFormat": "{{app_kubernetes_io_name}} - {{size}} - {{result}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 27 },
   "targets": [
    {
     "expr": "{namespace=\"schedule-mqtt-announcer\"} |= `WARN` or `ERROR` or `panic`"
    }
   ]
  }
 ]
}