{
 "title": "API adapter",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "API adapter requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(emf_schedule_adapter_requests_total[$__rate_interval])",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Errors: 2024",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{namespace=\"schedule-api-adapter\", app=\"api-adapter-2024\"} |= `WARN` or `ERROR` or `panic`"
    }
   ]
  },
  {
   "title": "Errors: 2022",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{namespace=\"schedule-api-adapter\", app=\"api-adapter-2022\"} |= `WARN` or `ERROR` or `panic`"
    }
   ]
  }
 ]
}