{
 "title": "Dial-a-Schedule",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Callers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(from) (dialaschedule_calls_total{status=\"Trying\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Call Status Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(dialaschedule_calls_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace, app_kubernetes_io_name, endpoint) (dialaschedule_requests_total)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Users Who Cannot Follow Simple Instructions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dialaschedule_user_error_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"dial-a-schedule\"} |= `WARN` or `ERROR` or `panic`"
    }
   ]
  }
 ]
}