---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: announcer
  namespace: dapnet-schedule-announcer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: announcer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: announcer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: announcer
          image: ghcr.io/dannixon/emfcamp-dapnet-schedule-announcer:e71b5b91beafe66fc81713dac7debbfe5146d19d
          env:
            - name: RUST_LOG
              value: info
            - name: API_URL
              value: http://http-2024.schedule-api-adapter.svc.cluster.local:8000/schedule
            - name: PRE_EVENT_ANNOUNCEMENT_TIME
              value: "300"
            - name: DAPNET_USERNAME
              value: m0nxn
            - name: DAPNET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dapnet-creds
                  key: password
