---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: announcer-dev
  namespace: schedule-mqtt-announcer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: announcer-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: announcer-dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: announcer
          image: ghcr.io/dannixon/emfcamp-schedule-mqtt-announcer:6ff4d99a491de8143631288efc0d9a662736e5f1
          env:
            - name: RUST_LOG
              value: debug
            - name: MQTT_BROKER
              value: mqtt-internal-pub.schedule-mqtt-announcer.svc.cluster.local
            - name: MQTT_PORT
              value: "18830"
            - name: MQTT_CLIENT_ID
              value: announcer-dev
            - name: MQTT_TOPIC_PREFIX
              value: emfcamp/schedule/announce/dev
            - name: PRE_EVENT_ANNOUNCEMENT_TIME
              value: "60"
            - name: API_URL
              value: http://http-2024.schedule-api-adapter.svc.cluster.local:8000/schedule?fake_epoch=2024-05-24T11:10:00%2b01:00
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
