---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-adapter-2024
  namespace: schedule-api-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-adapter-2024
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-adapter-2024
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: schedule-api-adapter
          image: ghcr.io/dannixon/emfcamp-schedule-api-adapter:a046765c3d309b98e4c017896598b8899f434e5a
          env:
            - name: RUST_LOG
              value: info
            - name: UPSTREAM_API_URL
              value: https://www.emfcamp.org/schedule/2024.json
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: http-2024
  namespace: schedule-api-adapter
spec:
  selector:
    app.kubernetes.io/name: api-adapter-2024
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http
