#
# This is a generated file!
#

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: dad-joke-hotline
spec:
  secretName: tls-cert
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-cloudflare-prod
    kind: ClusterIssuer
  dnsNames:
    - dad-joke-hotline.emfcamp.dan-nixon.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dad-joke-hotline
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: backend
          image: ghcr.io/dannixon/dad-joke-hotline:78992b8f28d26bb856d801f4be7242d031bde5c7
          env:
            - name: RUST_LOG
              value: info
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: dad-joke-hotline
spec:
  selector:
    app.kubernetes.io/name: backend
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https
  namespace: dad-joke-hotline
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`dad-joke-hotline.emfcamp.dan-nixon.com`)
      services:
        - Kind: Service
          name: http
          port: 8000
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Namespace
metadata:
  name: dad-joke-hotline
