#
# This is a generated file!
#

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: dial-a-schedule
spec:
  secretName: tls-cert
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-cloudflare-prod
    kind: ClusterIssuer
  dnsNames:
    - dial-a-schedule.emfcamp.dan-nixon.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dial-a-schedule
  namespace: dial-a-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dial-a-schedule
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dial-a-schedule
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: backend
          image: ghcr.io/dannixon/emfcamp-dial-a-schedule:07b208a18ae70986b6ac3af7375091df80d6a526
          env:
            - name: RUST_LOG
              value: info
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: dial-a-schedule
spec:
  selector:
    app.kubernetes.io/name: dial-a-schedule
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https
  namespace: dial-a-schedule
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`dial-a-schedule.emfcamp.dan-nixon.com`)
      services:
        - Kind: Service
          name: http
          port: 8000
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Namespace
metadata:
  name: dial-a-schedule
