#
# This is a generated file!
#

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: schedule-api-adapter
spec:
  secretName: tls-cert
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-cloudflare-prod
    kind: ClusterIssuer
  dnsNames:
    - schedule.emfcamp.dan-nixon.com
    - 2024.schedule.emfcamp.dan-nixon.com
    - 2022.schedule.emfcamp.dan-nixon.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-adapter-2022
  namespace: schedule-api-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-adapter-2022
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-adapter-2022
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: schedule-api-adapter
          image: ghcr.io/dannixon/emfcamp-schedule-api-adapter:a046765c3d309b98e4c017896598b8899f434e5a
          env:
            - name: RUST_LOG
              value: info
            - name: UPSTREAM_API_URL
              value: https://www.emfcamp.org/schedule/2022.json
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: http-2022
  namespace: schedule-api-adapter
spec:
  selector:
    app.kubernetes.io/name: api-adapter-2022
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-adapter-2024
  namespace: schedule-api-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-adapter-2024
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-adapter-2024
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: schedule-api-adapter
          image: ghcr.io/dannixon/emfcamp-schedule-api-adapter:a046765c3d309b98e4c017896598b8899f434e5a
          env:
            - name: RUST_LOG
              value: info
            - name: UPSTREAM_API_URL
              value: https://www.emfcamp.org/schedule/2024.json
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: http-2024
  namespace: schedule-api-adapter
spec:
  selector:
    app.kubernetes.io/name: api-adapter-2024
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https-2022
  namespace: schedule-api-adapter
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`2022.schedule.emfcamp.dan-nixon.com`)
      services:
        - Kind: Service
          name: http-2022
          port: 8000
  tls:
    secretName: tls-cert
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https
  namespace: schedule-api-adapter
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`schedule.emfcamp.dan-nixon.com`)
      services:
        - Kind: Service
          name: http-2024
          port: 8000
  tls:
    secretName: tls-cert

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https-2024
  namespace: schedule-api-adapter
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`2024.schedule.emfcamp.dan-nixon.com`)
      services:
        - Kind: Service
          name: http-2024
          port: 8000
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Namespace
metadata:
  name: schedule-api-adapter
