---
name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  formatting:
    name: Formatting and Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11

      # Evaluate the devshell here so that the time reported for subsequent
      # steps that use it reflect what is actually done there.
      - name: Evaluate devshell
        run: nix develop

      - name: Format
        run: nix develop --command treefmt --fail-on-change

  cloud-apps:
    name: Cloud Apps
    runs-on: ubuntu-latest
    needs:
      - formatting

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11

      # Evaluate the devshell here so that the time reported for subsequent
      # steps that use it reflect what is actually done there.
      - name: Evaluate devshell
        run: nix develop

      - name: Render all manifests
        run: |
          eval "$(nix print-dev-env)"
          ./cloud-apps/render_all.sh

      - name: Check committed manifests are up to date
        run: git diff --exit-code

  thermal-printer-flyers:
    name: Thermal Printer Flyers
    runs-on: ubuntu-latest
    needs:
      - formatting

    defaults:
      run:
        working-directory: "./thermal-printer-flyers"

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11

      # Evaluate the devshell here so that the time reported for subsequent
      # steps that use it reflect what is actually done there.
      - name: Evaluate devshell
        run: nix develop

      - name: Clippy
        run: nix develop --command cargo clippy --all-targets -- -D warnings

      - name: Build
        run: nix develop --command cargo build --all-targets
